# hyprlock.conf - Omarchy exact layout synced with Noctalia theme (Colors & Font)

$color = rgb(291514)
$inner_color = rgba(452321dd)
$outer_color = rgb(f5625a)
$font_color = rgb(f3f2f2)
$check_color = rgb(edf55a)
$topbar_color = rgba(291514ff)
$font = {{ui.fontDefault}}

## General configs
general {
    ignore_empty_input = true
    hide_cursor = false
}

auth {
    fingerprint:enabled = false
}

## Silky-smooth animations
animations {
    enabled = true
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    bezier = easeInExpo, 0.7, 0, 0.84, 0
    animation = fadeIn, 1, 6, easeOutExpo
    animation = fadeOut, 1, 4, easeInExpo
    animation = inputFieldDots, 1, 4, easeOutExpo
}

## Wallpaper
background {
    monitor =
    color = $color
    path = screenshot
    blur_passes = 5
}

## Password field
input-field {
    monitor =
    size = 550, 55
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4
    dots_size = 0.24
    dots_spacing = 0.24

    font_family = $font
    font_color = $font_color

    placeholder_text = <span size="smaller" alpha="50%">Enter Password</span>
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

## Top bar
shape {
    size = 100%, 52
    position = 0, 0
    halign = center
    valign = top
    color = $topbar_color
    border_size = 0
    rounding = 0
}

## Clock
label {
    text = $TIME
    font_size = 18
    halign = center
    valign = top
    position = 5, -9
    font_family = $font
    color = $font_color
}

## Right portion of top bar
label {
    text = cmd[update:2000] hyprlock-bar-right
    font_size = 18
    text_align = right
    halign = right
    valign = top
    position = -32, -9
    font_family = $font
    color = $font_color
}

## System info line
label {
    text = cmd[update:3600000] hyprlock-system-info
    font_size = 13
    halign = center
    valign = bottom
    position = 0, 50
    font_family = $font
    color = $font_color
}

## KVM label
label {
    text = cmd[update:2000] bash -c 'grep -q "Name=\"CX 2.4G Wireless Receiver Keyboard\"" /proc/bus/input/devices && echo "KVM"'
    font_size = 10
    halign = center
    valign = center
    position = 380, 0
    font_family = $font
    color = $font_color
}


## Audio Visualizer (Real PipeWire Spectrum)
label {
    text = cmd[update:50] /home/amtia/.local/bin/hyprlock-visualizer
    font_size = 6
    halign = center
    valign = center
    position = 0, 36
    font_family = $font
    color = $outer_color
}

## Futuristic Now Playing HUD (Sci-Fi Badge)
label {
    text = cmd[update:1000] /home/amtia/.config/hypr/hyprlock-media
    font_size = 10
    text_align = center
    halign = center
    valign = center
    position = 0, -90
    font_family = $font
    color = $font_color
}

