-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  general = { gaps_in = 4, gaps_out = 4, border_size = 1, layout = "scrolling", extend_border_grab_area = 5 },
  decoration = { inactive_opacity = 1.0, dim_strength = 0.07, border_part_of_window = false, blur = { size = 6, passes = 2, xray = true }, shadow = { enabled = false, range = 8, render_power = 2 }, glow = { range = 4 } },
  input = { kb_layout = "us", kb_variant = "", kb_options = "" },
  cursor = { hide_on_key_press = true },
})

hl.env("XCURSOR_THEME", "phinger-cursors-dark")
hl.env("XCURSOR_SIZE", "30")
hl.env("HYPRCURSOR_THEME", "phinger-cursors-dark")
hl.env("HYPRCURSOR_SIZE", "30")

hl.env("BROWSER", "zen-browser")
hl.env("TERMINAL", "kitty")

hl.config({ scrolling = { follow_focus = false } })


hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl setcursor phinger-cursors-dark 30")
end)
