-- Niri-style silky smooth animation preset (fast, responsive, 60fps/144fps smooth)
hl.curve("smoothEase", { type = "bezier", points = { { 0.16, 1.0 }, { 0.3, 1.0 } } })
hl.curve("niriEaseOut", { type = "bezier", points = { { 0.22, 1.0 }, { 0.36, 1.0 } } })
hl.curve("niriClose", { type = "bezier", points = { { 0.25, 1.0 }, { 0.5, 1.0 } } })

hl.animation({ leaf = "global", enabled = true, speed = 4.0, bezier = "smoothEase" })
hl.animation({ leaf = "windows", enabled = true, speed = 3.8, bezier = "smoothEase" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.0, bezier = "smoothEase", style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3.5, bezier = "niriClose", style = "popin 85%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4.2, bezier = "smoothEase" })
hl.animation({ leaf = "border", enabled = true, speed = 3.5, bezier = "smoothEase" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 3.5, bezier = "smoothEase" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.0, bezier = "smoothEase" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4.0, bezier = "smoothEase", style = "slidevert" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.5, bezier = "smoothEase" })
