[preferred]
default = hyprland;gnome;gtk
org.freedesktop.impl.portal.FileChooser = gnome;gtk
org.freedesktop.impl.portal.ScreenCast = hyprland
org.freedesktop.impl.portal.Screenshot = hyprland
org.freedesktop.impl.portal.Secret = gnome;gtk
org.freedesktop.impl.portal.GlobalShortcuts = hyprland
